format = """
$username\
$os\
$hostname\
$localip\
$shlvl\
$directory\
$fill\
$git_branch\
$git_commit\
$git_state\
$git_status\
$c\
$cmake\
$dotnet\
$golang\
$java\
$gradle\
$lua\
$nodejs\
$php\
$python\
$rust\
$typst\
$conda\
$line_break\
$character
"""

add_newline = false
palette = 'catppuccin_mocha'

[username]
format =  '[$user]($style) on '
style_root = 'bold red'
style_user = 'bold peach'
show_always = true


[os]
format = '[$symbol]($style)'
disabled = false
style = "blue"

[os.symbols]
Arch = " "


[hostname]
format = '[$ssh_symbol$hostname]($style) '
ssh_only = false
style = 'bold blue'


[shlvl]
disabled = false
symbol = ""
threshold = 3


[directory]
format = 'in [$path]($style)[$read_only]($read_only_style) '
home_symbol = ' '


[shell]
disabled = true
format = "using [$indicator]($style) "
fish_indicator = ' fsh'
style = "red"


[character]
success_symbol = '[](bold blue)'
error_symbol = '[](bold red)'

[git_branch]
format = ' on [$symbol$branch(:$remote_branch)]($style) '
symbol = ' '


[memory_usage]
disabled = true
format = '$symbol[${ram}( | ${swap})]($style) '
symbol = '󰍛 '
threshold = 0


[fill]
symbol = ''


[time]
disabled = false



[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavander = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

